### ISSUE TITLE
Feature Request: Different font for the keys

### ISSUE THREAD

**Issue by MrMartin92** [vchrizz/ER-wizard-WireGuard#1]
Hi,

first of all thank you for this amazing wizard.

I established a wireguard connection between my mobile device and my edgerouter in under 10 minutes. The most difficult part was to transfer the public key to my phone. Because I done it manually, differentiate between lowercase "L" and uppercase "I" was impossible. Is it possible to use a different font for the keys?

But all in all nice work 👍

**Comment by vchrizz** [comment]
Hi,

thanks for the hint, I have set font-family;courier for the public key info field.
What possibilities do you have to transfer the public-key, or what would help so you don't have to do it manually?

Thanks!

**Comment by MrMartin92** [comment]
Hi,

after the auto update, the letters are now much better distinguishable. Thanks.

> What possibilities do you have to transfer the public-key, or what would help so you don't have to do it manually?

The Wireguard app has the possibility to import a file/archive or to scan a QR code to import a complete configuration. But I'm unsure if this is a little bit too much for the wizard, because the configuration includes the private key of the peer, which must be generated on the router then. But it would be cool, that's for sure. If I'm not mistaken, the luci-app-wireguard for OpenWrt has this feature.

I don't know how other people are handling the transfer of the public key to and from the router. I'm only using two devices, so transferring them manually is the easiest, quickest and secure way I could think of.

**Comment by vchrizz** [comment]
Hi,
I could imagine to maybe do some file or QRcode generation so you could download and import the public/preshared key.
But I'm not sure if generating QRcode bloats the wizard.
I will look into this to see what is possible, which Wireguard app on which OS do you use?

**Comment by MrMartin92** [comment]
> which Wireguard app on which OS do you use?

I use iOS/iPadOS and Android with the official Apps.

- [AppStore (iOS)](https://apps.apple.com/us/app/wireguard/id1441195209?ls=1)
- [PlayStore (Andoird) ](https://play.google.com/store/apps/details?id=com.wireguard.android)
- [F-Droid (Andoird) ](https://f-droid.org/en/packages/com.wireguard.android/)

**Comment by vchrizz** [comment]
Added QR code for public key. See commit 9125f982 or release [v1.2-20211209](https://github.com/vchrizz/ER-wizard-WireGuard/releases/tag/v1.2-20211209)
So I assume this issue can be closed ? :)
(configuration export for app is another feature request, at least its not what the topic says I guess?)
