### ISSUE TITLE
Invalid QR Code

### ISSUE THREAD

**Issue by Zamana** [vchrizz/ER-wizard-WireGuard#12]
Hi!

I'm sorry for my dumbness, but I'm completely unable to make Wireguard works on my EdgeRouter-X (v2.0.9-hotfix.5) by following this wizard...

By some reason the QR Code is invalid after the initial configuration:

![image](https://user-images.githubusercontent.com/6900313/212556548-bc15436c-b74f-49e9-b050-d212c943ece4.png)

Are there more specific instructions than the screenshot?

**Comment by vchrizz** [comment]
How and where did you use the QR Code?
I just tried it and it works fine, so I would ask you to describe in detail what you do and what you expect, then I may be able to help you.
Sorry, my crystal ball is broken, so I am not able to know at what step exactly the QR Code is not working. ;)

**Comment by Zamana** [comment]
Sorry for the lack of information. I was really lost.

After filling the Publick Key in the Configuration section, I was able to generate a valid QR Code and now my client is connecting.

The only missing point now (I guess) is that I can't navigate on internet or access any of my internal hosts, but I think this is another issue not related with this wizard.

I'm sorry for bothering you.
