### ISSUE TITLE
All WireGuard config removed after EdgeOS update

### ISSUE THREAD

**Issue by samboman** [vchrizz/ER-wizard-WireGuard#16]
When I recently updated to EdgeRouter X v2.0.9-hotfix.6 (from hotfix.5) all my WireGuard config was gone. I had the same issue when I updated to hotfix.5, so I took a config-backup before and restored it after the update (when I saw all WireGuard was gone).

Just to know it was not related to a restart, I have restarted the device several times, ant the WireGuard config survives.

This is a big issue for me as I have to do the update on site and also I don't feel 100% secure with the solution. Can the config be blown away by any other action...

![image](https://user-images.githubusercontent.com/1038277/225016980-234503b1-be8b-4c5c-9d17-778e0903b4cf.png)

I'm happy to provide the information needed to find out why this happen, just let me know. Is it related to the wizard, can I just remove the wizard and have the config in the config-tree?

**Comment by avocadosalsa** [comment]
Do you think you might be running into issue #11?

**Comment by samboman** [comment]
Maybe, it can be related.
I checked and I did not have the directory `/config/scripts/pre-config.d` so I added it.

**Comment by samboman** [comment]
I got the same issue with the last EdgeOS update. I managed to restore backup via UISP.com cloud service. 👍  

How can I help to find a solution to this? Am I the only one facing tis issue?

**Comment by samboman** [comment]
How can I help to find a solution to this? Am I the only one facing tis issue?

**Comment by User-user00** [comment]
> How can I help to find a solution to this? Am I the only one facing this issue?

Check here... https://github.com/mafredri/vyatta-wireguard-installer

**Comment by vchrizz** [comment]
Please check out [v1.7-20230916](https://github.com/vchrizz/ER-wizard-WireGuard/releases/tag/v1.7-20230916).
This issue should now be fixed.

**Comment by samboman** [comment]
How do I update to 1.7?
<img width="478" alt="image" src="https://github.com/vchrizz/ER-wizard-WireGuard/assets/1038277/b9456aad-1c64-488c-b38c-a58a2f391d9d">
