### ISSUE TITLE
QR code seems incomplete

### ISSUE THREAD

**Issue by guillaumezin** [vchrizz/ER-wizard-WireGuard#17]
Hello,
I'm trying to generate a configuration but I'm unable to use it on an android phone: the QR code contains only:
```
[Interface]
PrivateKey = xxxxx

[Peer]
PublicKey = yyyyy
PresharedKey = zzzzz
```

To work I should have at least, I think:
```
[Interface]
PrivateKey = xxxxx
Address = aaaaa

[Peer]
PublicKey = yyyyy
PresharedKey = zzzzz
AllowedIPs = 192.168.0.0/24
Endpoint = addressofedgerouter:portofwireguard
```

I'm using Firefox 112 on Ubuntu 22.04 and EdgeRouter X v2.0.9-hotfix.6

**Comment by guillaumezin** [comment]
Let me be more specific:
- Address in [Interface] from QR code should be Allowed IPs of the wizard
- Endpoint in [Peer] from QR code should be Remote endpoint of the wizard
- PersistentKeepalive in [Peer] from QR code should be Keepalive of the wizard
- I would add a text input to define AllowedIPs in [Peer] from QR code
- I would add a text input to optionnaly define DNS in [Interface] from QR code

And by the way, when generating the QR code, could you show the peer private key in a selectable text area? I use KDE Plasma and it cannot take QR code directly, it would be easier to copy paste generated private key.

Thank you.

**Comment by Dude4Linux** [comment]
@guillaumezin You have a typo in the code that sets PersistentKeepalive in the QRcode which results in an invalid QRcode. The alt-text shows the name is 'nPersistentKeepalive'. 

`    if (persistentkeepalive) {
        config += "\nnPersistentKeepalive = " + persistentkeepalive;
    }
`
There is also an indexing issue with the address. All QRcodes get the address of the first peer.

**Comment by guillaumezin** [comment]
Thank you. I will correct the typo.

But I can't reproduce the issue with the address. I will try to code it another way, maybe it depends on edgeos version.

**Comment by vchrizz** [comment]
Thank you very very much for your contributions!
#18 merged, so this issue can be closed I guess?
