### ISSUE TITLE
Apply function is deleting some wireguard interface settings

### ISSUE THREAD

**Issue by tekert** [vchrizz/ER-wizard-WireGuard#19]
I noticed the script deletes the `wireguard interface $wgx` node to "readd" the settings, the problem with this aproach is that it deletes the following config each time the wizard is applied:
```
description
down-command
fwmark
up-command
```
It would be better to modify existing settings instead of deleting the interface config, in case new settings are added to wireguard too.

**Comment by tekert** [comment]
Made some fixes for this in #20 Need some input to review.

**Comment by vchrizz** [comment]
Thank you very very much for your contributions!
#20 merged, so this issue can be closed I guess?

**Comment by tekert** [comment]
Yes, if config restoration doesn't work after a firmware update i'll make another pull request.
