### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by User-user00** [vchrizz/ER-wizard-WireGuard#21]
I see some pull requests that look to be beneficial, but the author is showing very little activity this year.  This is a great package and would hate for it to fall by the wayside.  Anyone?

**Comment by vchrizz** [comment]
Yes, I still have an eye on it, but lately I don't get the time to look at the code.
I thank everybody for the pull requests!

There are two options for immediate action:
- I blindly merge the pull-requests, without checking anything.
- Someone cross-checks the pull-requests in detail and acknowledges(four eye principle), so I can safely merge them.

Else please wait until I get the time to check the pull-requests, I am not paid and do this in my spare time.
Thank you!

**Comment by User-user00** [comment]
You do great work and that package is really incredible.  Thanks for all your efforts and contributions to the community!
