### ISSUE TITLE
Remove Peer doesn't actually remove the peer

### ISSUE THREAD

**Issue by jumperalex** [vchrizz/ER-wizard-WireGuard#26]
Clicking "Remove Peer" deletes the peer from the Wizard, and clicking "Apply" seems implies that the peer is removed. But upon refresh, or "wg" in CLI, or viewing the config in the ER UI the peer is still there. Using the ER UI to remove the peer works and a refresh of the Wizard confirm it. 

Version 1.7

**Comment by vchrizz** [comment]
Hopefully fixed with #25
