### ISSUE TITLE
clarify what happens to other wg interfaces

### ISSUE THREAD

**Issue by sslupsky** [vchrizz/ER-wizard-WireGuard#3]
This is an interesting wizard.  Thank you.  I do have a question that does not appear to be addressed in the installation instructions.  That is, what happens when "Setup Script" is enabled and you have multiple wireguard interfaces?  I can see that the script configures wg0 according to the wgsettings.json file.  What if there is another wg interface enabled when the setup script is run?  Will those interface's configuration be the same as it was before the script executed?  The instructions say wg1-wg999 are "untouched" so I expect that if for instance if wg1 is configured, it will still be configured the same way after the setup script runs?

**Comment by sslupsky** [comment]
Also, I notice that the wizard seems to take a long time to run when you click on it.  Sometimes it just sits there wth a spinning gear and I have to refresh the page.  Is this "normal"?

**Comment by vchrizz** [comment]
> The instructions say wg1-wg999 are "untouched" so I expect that if for instance if wg1 is configured, it will still be configured the same way after the setup script runs?

Correct, at the moment only wg0 settings are saved to wgsettings.json and only those are loaded again if the setup script runs.
Other interfaces stay untouched but as soon as you install a firmware (and setup script runs to install wireguard), settings from other interfaces are lost.

If I understand, your request is to save other interfaces too, so on a firmware upgrade those get loaded again?

**Comment by vchrizz** [comment]
> Also, I notice that the wizard seems to take a long time to run when you click on it. Sometimes it just sits there wth a spinning gear and I have to refresh the page. Is this "normal"?

(Depending on your system and connection to the EdgeMax router) The loading time should be typically within about 5-10 seconds or so. Depending on what you did (before running the WireGuard wizard) in the EdgeOS UI it could be that you need a browser refresh. That is "normal".
After a browser refresh or on first load (like after the initial login to EdgeOS UI) the wizard should not load that long.
Else you could look into the browser console if there maybe is some issue.

**Comment by doc-jay** [comment]
I would expect that any existing wg$ interfaces would remain untouched and come back after a new firmware.  I've got three interfaces and would be disappointed if they didn't come back after a firmware update.

**Comment by sslupsky** [comment]
> If I understand, your request is to save other interfaces too, so on a firmware upgrade those get loaded again?

Yes, I would like to be able to do an EdgeOS update without worry that my wg interface settings are reset.

**Comment by vchrizz** [comment]
I released wizard v1.5 - all wireguard related settings should now be kept, even after a firmware upgrade.
If you had setup-script enabled, it could be that you need to disable&apply and/or just enable&apply (again) to make this work.
Please try and report if it also works for you as expected, in my test environment this works fine.

**Comment by vchrizz** [comment]
I guess this issue can be closed? If you notice any issues regarding this topic, please reopen and describe in detail, thanks.
