### ISSUE TITLE
ER-4 in-place upgrade report

### ISSUE THREAD

**Issue by User-user00** [vchrizz/ER-wizard-WireGuard#5]
Device ER-4 v2.0.9hf2
WG Wizard 1.5
Installed WG : 1.0.20210424-1

Wizard properly detected older version needing update.
info: wireguard 1.0.20210424-1 installed. new version found: 1.0.20210606-3

Settings missed/skipped:

Route allowed IPs - I have it disabled and the wizard properly detected it by not checking it, but when I clicked apply - it still shows unchecked - but when you refresh the browser or check the CLI - the setting is checked/true.  Had to manually revert to false via CLI.

WG IP Address
As mentioned in another post - the 
"set interfaces wireguard wg0 address" entry is blank.
Appears to be no entry in Wizard, so put it back via CLI

Descriptions
All of my descriptions disappeared.
This is helpful when the only identifier is the public peer key.
Can you add this field back?

Almost forgot - even with those unexpected changes - the update itself worked great once I clicked "Apply" - which was easily restored via CLI.

Thanks!

**Comment by vchrizz** [comment]
> Route allowed IPs - I have it disabled and the wizard properly detected it by not checking it, but when I clicked apply - it still shows unchecked - but when you refresh the browser or check the CLI - the setting is checked/true. Had to manually revert to false via CLI.

fixed in https://github.com/vchrizz/ER-wizard-WireGuard/commit/4abde4fcb1353100ba784d10fcc1f47f2d705e20

**Comment by vchrizz** [comment]
> WG IP Address As mentioned in another post - the "set interfaces wireguard wg0 address" entry is blank. Appears to be no entry in Wizard, so put it back via CLI

added in https://github.com/vchrizz/ER-wizard-WireGuard/commit/5f34ac073feb8310d3e007d6aa68b119cbfff383

**Comment by vchrizz** [comment]
> Descriptions All of my descriptions disappeared. This is helpful when the only identifier is the public peer key. Can you add this field back?

added.

**Comment by vchrizz** [comment]
Should work now with [release version 1.6](https://github.com/vchrizz/ER-wizard-WireGuard/releases/tag/1.6-20211226).
Please reopen this issue if you encounter any problems. Thanks.
