### ISSUE TITLE
ER-wizard can't detect public/private-key if a path to the private key and not the key itselfs is given in configuration.

### ISSUE THREAD

**Issue by mwawra** [vchrizz/ER-wizard-WireGuard#6]
First of all, thanks for the great tool!
I was wondering why I get "N/A" for the server's (not the peers) public key.
I think the problem is due to the combination of my configuration and the way ER-wizard-WireGuard tries to get the private key.
In the wizard-run file at line 312:
`eval "privatekey=($($cli returnActiveValue interfaces wireguard ${interfaces[0]} private-key))"`
returns not the private key itself but the path to the file which contains the key (e.g. /config/auth/wg.key).
Then also line 314 fails:
`localpubkey=$(echo "$privatekey" | /usr/bin/wg pubkey)`
Maybe something like
`eval "privatekey=($($run show interfaces wireguard ${interfaces[0]} private-key))"`
is more robust?

**Comment by IndrekHaav** [comment]
I can confirm the proposed change works - public key is shown correctly if private key is stored in file.

**Comment by vchrizz** [comment]
Thank you @mwawra for the proposed change. Thank you @IndrekHaav for confirming this change.
To be honest I did not know it is possible to specify a file there so I went ahead this way.
I'll update the wizard to reflect this change.
