### ISSUE TITLE
Wizard seems to nuke configurations on update.

### ISSUE THREAD

**Issue by razor950** [vchrizz/ER-wizard-WireGuard#7]
I had a few peers prior to applying an update via the wizard and it nuked a few of the peers on my list. I am not sure why it didn't nuke it all and only a few.

a solution for this would be to add a import / export for WG settings to prevent that from being an issue.

**Comment by vchrizz** [comment]
Could you describe in detail how to reproduce the issue?
I tested the update with several configurations but most had only one or two peers configured.

The wizard basically is just a frontend for the EdgeOS ConfigTree.
Reimplementing existing functionality is not quite the purpose of the wizard functionality.
If you want to back up your configuration, you can download a backup in EdgeOS GUI.
If you do not want the full EdgeOS backup and only want the wireguard configuration lines, you can grab them on the shell:
`show configuration commands | grep wireguard`

Importing the backup works similar as getting the backup:
In EdgeOS GUI you can import/upload a full EdgeOS backup.
On the shell you can enter `configure` then paste the lines from your backup then do `commit` and `save` (and `exit` to leave configure mode).

**Comment by samboman** [comment]
Maybe its related to this: #10

**Comment by vchrizz** [comment]
(as also noted in #10)
There have been changes in config management and before I used /config/user-data/wireguard/wgsettings.json but in the latest release of Wireguard Wizard this file is stale and should be removed. Could you check if you have latest (1.6) version of the wizard running and check that you do not have the wgsettings.json file? If the file is there, rename it and check if the issue happens again. If you still encounter the issue, feel free to reopen.
